### ISSUE TITLE
Need updated Icon and Share graphics

### ISSUE THREAD

**Issue by vivachu** [vivachu/pet-cross#15]
Need to update these art assets.  @kuswanto we need these for pet-dig and pet-cross.

http://stage-minigames.parade.pet/pet-cross/assets/pics/icon.png
http://stage-minigames.parade.pet/pet-cross/assets/pics/notification/0.png
http://stage-minigames.parade.pet/pet-cross/assets/pics/notification/1.png ... 10.png
http://stage-minigames.parade.pet/pet-cross/assets/pics/notification/animated.png

**Comment by kuswanto** [comment]
Here's icon for Petcross
![0](https://user-images.githubusercontent.com/1097842/36776665-2b526d34-1c99-11e8-8fcc-47e73d405d27.png)
![icon](https://user-images.githubusercontent.com/1097842/36776666-2b838a2c-1c99-11e8-9bde-6a8eb54579d6.png)

**Comment by ErwinPS** [comment]
done

**Comment by kuswanto** [comment]
![animated](https://user-images.githubusercontent.com/1097842/36832997-8cb01e6a-1d60-11e8-8a3b-0ad77e7c766a.png)
![icon](https://user-images.githubusercontent.com/1097842/36832998-8cef0cc4-1d60-11e8-93da-d3075d21f637.png)

Update of the icon.

**Comment by vivachu** [comment]
Hi @kuswanto Yes we also need the png sequences as well.

**Comment by vivachu** [comment]
@ErwinPS Please update the assets/pics directory with the attached zip file of assets for the icon and notifications images.  
[pics.zip](https://github.com/vivachu/pet-cross/files/1794333/pics.zip)

**Comment by vivachu** [comment]
@kuswanto Please paste the updated notification icon in this ticket for @ErwinPS to include.  Please use the same format as this zip: [pics.zip](https://github.com/vivachu/pet-cross/files/1794333/pics.zip)

**Comment by ErwinPS** [comment]
done
