### ISSUE TITLE
Integrate with server side API

### ISSUE THREAD

**Issue by vivachu** [vivachu/pet-cross#18]
Need to integrate with server side API.

You can use this token as a test: `eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzaWQiOjIyODU4NiwiaWF0IjoxNTE5Mzk5NTU5fQ.YSziFbOT4SOjUZhQCuO_5-zjNYDNisjesUi_atlQIQo`

**Comment by vivachu** [comment]
Here are the full query params to test:  

`?apiUrl=https://stage-api.parade.pet/&assetUrl=http://stage-assets.parade.pet/&token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzaWQiOjIyODU4NiwiaWF0IjoxNTE5Mzk5NTU5fQ.YSziFbOT4SOjUZhQCuO_5-zjNYDNisjesUi_atlQIQo`

**Comment by vivachu** [comment]
Is this working?

**Comment by ErwinPS** [comment]
done by Hari, backend is his area
