### ISSUE TITLE
Transitional sound effect screen between end and bonus

### ISSUE THREAD

**Issue by vivachu** [vivachu/pet-cross#22]
We need some transitional screen between the user's last life and the bonus screen similar to Pet Dig.  It's strange to play the congrats message right after you just lost your life.

**Comment by ErwinPS** [comment]
when game over, the screen still go to the victory screen but the title changed and the confetti removed

**Comment by vivachu** [comment]
The congratulations screen needs to remain the same.  See the transition screen for the Pet Dig game.
<img width="375" alt="image" src="https://user-images.githubusercontent.com/365217/36824515-cba2f0c4-1cd0-11e8-9cb2-57649767ec9c.png">

For Pet Cross, make the transition screen say:  

```
           GAME OVER 
You went 25 steps in 2 lives. 
        [ CLAIM BONUS ]
```
Replace the number of steps with the number of steps the user was able to achieve and the number of lives with the number of lives they used up.

**Comment by ErwinPS** [comment]
Done
