### ISSUE TITLE
Pet picture has hole in it

### ISSUE THREAD

**Issue by vivachu** [vivachu/pet-cross#30]
On initial load of the game, the pet picture has a hole in it.  See screenshot.
<img width="375" alt="image 49" src="https://user-images.githubusercontent.com/365217/36920490-d9a75318-1e2e-11e8-8624-71e428072f74.png">

**Comment by vivachu** [comment]
Note this only seems to happen on iOS.

**Comment by ErwinPS** [comment]
this is caused by the z-order,. I have reprogram the z-order mechanism in the game to solve this.
