### ISSUE TITLE
Calculate the user's score and report to /minigame/end

### ISSUE THREAD

**Issue by vivachu** [vivachu/pet-cross#35]
Currently 0 is being passed as the score.  The score should be calculated as follows: 

`(numStepsForward)+(numLivesRemaining)+Math.max(0, 120-secondsElapsed)
`
Examples
If the user made it 120 steps with 1 life remaining and took 110 seconds then the score would be 120+1+10 = 131.  

NOTE that the numLivesRemaining is the number of lives that the user has at the end of the game.  This number is not zero ONLY if the user completed the whole course with extra lives left.

**Comment by ErwinPS** [comment]
with this formula, when the user lost all their lives but playing only few seconds, the score is bigger than complete play, so I change the formula to : 
(numStepsForward)+(numLivesRemaining)*Math.max(0, 120-secondsElapsed)
so the bigger numLivesRemaining the bigger the score is

**Comment by vivachu** [comment]
The score being reported to the server is always 0.  Are we sure we are using the correct formula?

`(numStepsForward)+(numLivesRemaining)*Math.max(0, 120-secondsElapsed)`

Examples (assumes that 200 is the max number of steps forward)
- 17 steps, 20 seconds, 0 lives remaining  = 17 score
- 200 steps, 100 seconds, 0 lives remaining = 200 score
- 200 steps, 100 seconds, 1 life remaining = 220 score
- 200 steps, 100 seconds, 2 lives remaining = 240 score
- 200 steps, 130 seconds, 1 life remaining = 200 score

**Comment by vivachu** [comment]
@ErwinPS Please confirm that the max number of steps forward is currently set to 200?

**Comment by ErwinPS** [comment]
the total step is fixed to 200 steps. the score now sent to backend
